name: Node.js CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get version
      run: |
        /usr/bin/git fetch --tags
        echo "VERSION=$(git describe --abbrev=0 --tags --always)" >> $GITHUB_ENV
    - name: Set version
      run: |
        sed -i -e "s/>0.0.0</>$VERSION</" ./package.json
        cat ./package.json
    - run: npm ci
    - run: npm test
  
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_AUTOMATION_KEY}}
    - name: Publish Package to npmjs.com
      run: npm publish --dry-run
